version: 0.2

env:
  variables:
    REPO_NAME: "demo-node-app-repo"
phases:
  install:
    runtime-versions:
      nodejs: 18
      docker: 20
    commands:
      - echo "Installing dependencies"
      - cd app
      - npm ci
      - cd ..
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - cd app
      - docker build -t demo-node-app:latest .
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO=$REPO_NAME
      - docker tag demo-node-app:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO:latest
  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO=$REPO_NAME
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO:latest
artifacts:
  files:
    - '**/*'
